#!/usr/bin/env node
// build-mirror.mjs — generate html/index.html, a no-JS static mirror of index.html.
//
// The live site (index.html) holds the single source of truth in the inline `MITH`
// object. This script extracts that object and renders a plain, JavaScript-free page
// for text browsers, emacs eww, lynx/w3m, and screen readers. Run before pushing:
//
//     node tools/build-mirror.mjs
//
// No dependencies. GPL-3.0.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = readFileSync(join(root, 'index.html'), 'utf8');

// --- extract MITH (the single source of truth) and evaluate it in a window shim ---
const m = src.match(/window\.MITH\s*=\s*\(function\(\)\{[\s\S]*?\}\)\(\);/);
if (!m) { console.error('could not find the MITH object in index.html'); process.exit(1); }
const window = {};
// eslint-disable-next-line no-eval
eval(m[0].replace(/^window\.MITH/, 'window.MITH'));
const MITH = window.MITH;
if (!MITH || !MITH.ver) { console.error('MITH did not evaluate to an object'); process.exit(1); }

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
// keep the tiny inline tags MITH uses for copy (<code>, <b>) but escape everything else
const rich = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/&lt;(\/?)(code|b)&gt;/g, '<$1$2>');

const R = MITH.repo;
const ext = (href) => /^https?:/.test(href);
const link = (label, href) => {
  const h = href.startsWith('#') ? href : href;            // anchors map to sections below
  const target = ext(h) ? ' target="_blank" rel="noopener"' : '';
  return `<a href="${esc(h)}"${target}>${esc(label)}</a>`;
};

const products = MITH.order.map((k) => {
  const p = MITH.products[k];
  const meta = p.meta.map(([dt, dd]) => `      <dt>${esc(dt)}</dt><dd>${esc(dd)}</dd>`).join('\n');
  const acts = p.actions.map(([label, href]) => link(label, href)).join(' &nbsp;·&nbsp; ');
  return `  <article id="${esc(p.name)}">
    <h3>${esc(p.name)} <small>${esc(p.latin)}</small></h3>
    <p class="status">${esc(p.codename)} &nbsp;·&nbsp; ${esc(p.status)}</p>
    <p>${rich(p.desc)}</p>
    <p class="sub">— ${rich(p.sub)}</p>
    <dl>
${meta}
    </dl>
    <p class="actions">${acts}</p>
  </article>`;
}).join('\n');

const skills = MITH.skills.map((s, i) => {
  const n = String(i + 1).padStart(2, '0');
  const href = `${R.skills}/tree/main/${s.slug}`;
  return `    <li><b>${n}</b> <a href="${esc(href)}" target="_blank" rel="noopener">${esc(s.title)}/</a> — ${esc(s.summary)}</li>`;
}).join('\n');

const releases = MITH.releases.map((r) =>
  `  <article>
    <h3>${esc(r.repo)} <small>${esc(r.tag)} · ${esc(r.date)}</small></h3>
    <p><b>${esc(r.title)}</b></p>
    <p>${rich(r.body)}</p>
  </article>`).join('\n');

const out = `<!doctype html>
<!--
  Mithraeum — plain mirror of ${R.site}
  Copyright (C) 2026 Mithraeum. GPL-3.0 (see ../LICENSE).
  GENERATED by tools/build-mirror.mjs from index.html's MITH object. Do not edit by hand.
  No JavaScript, no fonts, no third-party request, no tracker. Readable in emacs eww,
  lynx, w3m, any text browser, any screen reader. ⇩ download and read it offline.
-->
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Mithraeum — plain mirror</title>
<meta name="viewport" content="width=device-width,initial-scale=1" />
<meta name="referrer" content="no-referrer" />
<style>
  :root{ --void:#0a0a09; --bone:#c8c2b2; --paper:#d8d2c2; --chalk:#e8e2d2; --ash:#6a665c; --gold:#b89656; --rule:#ffffff22; }
  *{box-sizing:border-box}
  body{ margin:0 auto; max-width:760px; padding:32px 20px 64px;
    background:var(--void); color:var(--bone);
    font-family:ui-monospace,Menlo,Consolas,monospace; font-size:15px; line-height:1.65; }
  a{ color:var(--gold); } a:hover{ color:var(--chalk); }
  h1,h2,h3{ font-family:Georgia,'Times New Roman',serif; color:var(--chalk); line-height:1.2; }
  h1{ font-size:30px; margin:0 0 6px; letter-spacing:0.04em; }
  h2{ font-size:22px; margin:40px 0 6px; border-top:1px solid var(--rule); padding-top:24px; }
  h3{ font-size:18px; margin:24px 0 4px; } h3 small{ color:var(--gold); font-family:ui-monospace,monospace; font-size:12px; font-weight:normal; }
  .eyebrow{ color:var(--gold); font-size:12px; letter-spacing:0.22em; text-transform:uppercase; }
  .status{ color:var(--ash); font-size:12px; letter-spacing:0.06em; }
  .sub{ color:var(--ash); font-size:13px; }
  .lede{ color:var(--paper); }
  dl{ display:grid; grid-template-columns:auto 1fr; gap:2px 14px; font-size:13px; margin:8px 0; }
  dt{ color:var(--ash); } dd{ margin:0; color:var(--paper); }
  ul{ list-style:none; padding:0; } li{ margin:6px 0; } li b{ color:var(--gold); }
  pre{ background:#14130f; border:1px solid var(--rule); padding:14px 16px; overflow-x:auto; font-size:13px; color:var(--paper); }
  code{ color:var(--paper); }
  footer{ margin-top:48px; border-top:1px solid var(--rule); padding-top:20px; color:var(--ash); font-size:12px; }
  .note{ color:var(--ash); font-size:12px; border:1px solid var(--rule); padding:10px 14px; margin:18px 0; }
</style>
</head>
<body>

<p class="eyebrow">— ORDO MITHRAEUM · MMXXVI —</p>
<h1>Tools for the inner chamber.</h1>
<p class="lede">A modal editor, a terminal agent, and the local models that run them — three C instruments on a from-scratch inference engine. No cloud, no telemetry, no daemon. Bring your own keys, or run our weights on-device.</p>
<p class="note">Plain mirror of <a href="${R.site}">${R.site}</a> — no JavaScript, no web fonts, no third-party request. The interactive version lives at the link above; this one is for text browsers, emacs <code>eww</code>, and offline reading.</p>

<h2>Suite — three instruments, one chamber</h2>
${products}

<h2 id="creed">Creed</h2>
<dl>
  <dt>Local first</dt><dd>Your text, your keys, your weights. No telemetry, no silent network, no daemon.</dd>
  <dt>Single binary</dt><dd>One C source. No JavaScript runtime to swallow your editor. The tool fits in a head.</dd>
  <dt>Bring your own model</dt><dd>Any model, any provider. A peer at your terminal, not a stranger in the cloud.</dd>
</dl>

<h2 id="install">Install</h2>
<pre># the agent
curl -fsSL ${R.site}/hako.sh | sh

# the editor
curl -fsSL ${R.site}/hake.sh | sh

# the engine — build from source (libc + libm + pthread only)
git clone ${R.models} &amp;&amp; cd hako &amp;&amp; make</pre>
<p>Each installer fetches the latest signed release for your OS/arch, verifies the sha256 sidecar, drops the binary in <code>~/.local/bin</code>. No package manager, no daemon, no telemetry.</p>

<h2 id="skills">Skills — behaviors for hako, by name</h2>
<p>Each is a folder in <a href="${R.skills}" target="_blank" rel="noopener">mithraeums/skills</a>: a <code>SKILL.md</code> plus helpers. Markdown only — works in hako and in Claude.</p>
<ul>
${skills}
    <li><b>··</b> <em>your skill here</em> — open a PR; the folder name becomes the invocation.</li>
</ul>

<h2 id="releases">Releases — latest from each chamber</h2>
${releases}

<footer>
  <p>© MMXXVI · ordo mithraeum · <a href="../LICENSE">GPL-3.0</a> · BUILD ${esc(MITH.build)}</p>
  <p><a href="${R.org}" target="_blank" rel="noopener">source ↗</a> ·
     <a href="index.html" download>⇩ this page</a> ·
     <a href="${R.discuss}" target="_blank" rel="noopener">discussions ↗</a> ·
     <a href="mailto:${esc(MITH.email)}">${esc(MITH.email)}</a></p>
  <p>— deus sol invictus mithras —</p>
</footer>

</body>
</html>
`;

mkdirSync(join(root, 'html'), { recursive: true });
writeFileSync(join(root, 'html', 'index.html'), out);
console.log(`wrote html/index.html — ${out.length} bytes · ver ${MITH.ver.hake}/${MITH.ver.hako}/${MITH.ver.engine} · ${MITH.skills.length} skills · ${MITH.releases.length} releases`);
